velcro-plate PR
RoboticsTeam4904/2019-Code pull request #11
Opened 2019-01-11 01:43 UTC by bcho04

**Summary**: 

This is a proposed pull request for the velcro-plate subsystem. Its function and actions can be summarized as follows: 

```
The default position of the pistons is in its "RELEASED" state,
with the motor in the upright position. The mechanism works by
doing the following actions in this order:
    (1) Rotate the plate to the floor to pick up the hatch via Velcro. No pistons should
        change state during this process.

    (2) Rotate back to the upright position.

    (3) Drive over to the hatch port location.

    (4) Attach the hatch to the location via piston extension, then after a split second drive
        away. This places the hatch in its target port.

    (5) Release pistons to reset the process.
```
Note that this is different from the proposal in the prototypes list.

---

**Visualization**:
The subsystem can be visualized as follows:
![velcroplate](https://user-images.githubusercontent.com/15110725/51008045-df2c9380-14fe-11e9-88bc-f3862c266570.png)

2019-01-12 07:21 UTC, NikhilSuresh24 requested changes
Good framework thus far, just a few changes to make the code more understandable for others. Also, this branch has merge conflicts with standard, so those should be sorted. Cool diagram btw.

2019-01-12 07:21 UTC, NikhilSuresh24 commented on .vscode/settings.json
> +  "python.pythonPath": "/usr/local/bin/python3"
Don't add your personal settings

2019-01-12 07:21 UTC, NikhilSuresh24 commented on src/main/java/org/usfirst/frc4904/robot/commands/PickupSolenoidSet.java
> +public class PickupSolenoidSet extends Command {
Make Commands called PickupSolenoidClasp and PickupSolenoidRelease that extend this command and just input true or false as input to make it clear what the inputs mean

2019-01-12 07:21 UTC, NikhilSuresh24 commented on src/main/java/org/usfirst/frc4904/robot/commands/PickupSolenoidRoutine.java
> +        addSequential(new PickupSolenoidSet(true));
Look at the comment in pickupSolenoidSet

2019-01-12 07:21 UTC, NikhilSuresh24 commented on src/main/java/org/usfirst/frc4904/robot/commands/PlaceSolenoidRoutine.java
> +        addSequential(new PlaceSolenoidSet(true));
See PickupSolenoidSet comment

2019-01-12 07:21 UTC, NikhilSuresh24 commented on src/main/java/org/usfirst/frc4904/robot/commands/PlaceSolenoidRoutine.java
> +        addParallel(new ChassisConstant(RobotMap.Component.chassis, MOTOR_MOVE_X, MOTOR_MOVE_Y, MOTOR_TURN, 0.0));
sorry i didn't notice this earlier, but the driver will likely be positioning the robot in front of the hatch, so no movement code is necessary

2019-01-12 07:21 UTC, NikhilSuresh24 commented on src/main/java/org/usfirst/frc4904/robot/commands/VelcroPlateDefault.java
> +        addParallel(new ChassisConstant(RobotMap.Component.chassis, MOTOR_HALT_X, MOTOR_HALT_Y, MOTOR_TURN, 0.0));
no chassis movement needed

2019-01-13 17:22 UTC, b-cho commented on .vscode/settings.json
> +  "python.pythonPath": "/usr/local/bin/python3"
I don't remember changing this, but it may have been done automatically. Should I just delete these changes in the file and re-commit?

2019-01-13 18:21 UTC, NikhilSuresh24 commented on .vscode/settings.json
> +  "python.pythonPath": "/usr/local/bin/python3"
yeah

2019-01-13 22:22 UTC, b-cho commented on src/main/java/org/usfirst/frc4904/robot/commands/PickupSolenoidSet.java
> +public class PickupSolenoidSet extends Command {
Finished that and applied this to `PlaceSolenoid` as well.

2019-01-20 22:53 UTC, bcho04 commented
I have merged the code in `velcro-plate` with that of the `floorio` branch at PR #5. Therefore, I am closing this pull request. Please see #5 for future suggestions.

2019-01-20 22:53 UTC, closed without merging