Chassis code
RoboticsTeam4904/2019-Code pull request #14
Opened 2019-01-14 23:53 UTC by josehrl

This is the chassis code, adapted from 2018 code.

2019-01-15 00:34 UTC, NikhilSuresh24 requested changes
Overall looks good. One main change needed for motorcontrollers.

2019-01-15 00:34 UTC, NikhilSuresh24 commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +            new VictorSP(Port.PWM.rightDriveA), new VictorSP(Port.PWM.rightDriveB));
Make these CANTalonSRX instead of VictorSP

2019-01-20 18:23 UTC, countableclouds commented
Just fixed PR changes...

2019-01-20 22:15 UTC, Daniel-E-B requested changes
I'm glad that `Component.driverXbox` got fixed :). Other than deciding on speed controllers, and either removing or using `STICK_RIGHT_DEADZONE` from `HumanInterfaceConfig`, this looks great!

2019-01-20 22:15 UTC, Daniel-E-B commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +import edu.wpi.first.wpilibj.VictorSP;
We almost definitely will not use victors this year. We will likely use talons (and maybe some sparks, which are now at `org.usfirst.frc4904.standard.custom.motioncontrollers.Spark`).

2019-01-20 22:15 UTC, Daniel-E-B commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +        HumanInput.Operator.joystick.setDeadzone(HumanInterfaceConfig.STICK_LEFT_DEADZONE);
the stick deadzone is set to`STICK_LEFT_DEADZONE`, and `STICK_RIGHT_DEADZONE` is left unused. What is the purpose of `STICK_RIGHT_DEADZONE` and where should it be used?

2019-01-20 22:22 UTC, countableclouds commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +        HumanInput.Operator.joystick.setDeadzone(HumanInterfaceConfig.STICK_LEFT_DEADZONE);
Talked to Billy, changing to JOYSTICK_DEADZ
ONE...

2019-01-20 22:25 UTC, Daniel-E-B submitted a review, later dismissed

2019-02-12 00:02 UTC, billwpierce reviewed
Looks Good --> I'm gonna to add config files and make a PR

2019-02-12 00:02 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +            public static final int leftDriveA = 24; //TODO: MIGHT CHANGE
Make all of these -1

2019-02-12 00:02 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +        public static class PWM {
delete if unused

2019-02-17 17:28 UTC, oshlern submitted a review, later dismissed

2019-02-17 17:28 UTC, oshlern commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +        Component.leftWheelEncoder.setDistancePerPulse(Metrics.Wheel.INCHES_PER_TICK);
Set in the constructor of leftWheelEncoder

2019-02-17 17:28 UTC, oshlern commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +        Component.rightWheelEncoder.setDistancePerPulse(Metrics.Wheel.INCHES_PER_TICK);
Set in the constructor of rightWheelEncoder

2019-02-17 17:28 UTC, oshlern commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +        Component.leftWheelB = new Motor("leftWheelB", true, Component.leftWheelAccelerationCap,
Combine A and B by calling the motor constructor with 2 CANTalonSRX inputs

2019-02-17 17:28 UTC, oshlern commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +        Component.drivePID = new CustomPIDController(PID.Drive.P, PID.Drive.I, PID.Drive.D, PID.Drive.F,
Use an EncoderPair to combine left and right encoders

2019-02-17 17:28 UTC, oshlern commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +        Component.drivePID = new CustomPIDController(PID.Drive.P, PID.Drive.I, PID.Drive.D, PID.Drive.F,
we didn't do this last year because one of the encoders was unplugged

2019-02-17 22:08 UTC, NikhilSuresh24 submitted a review, later dismissed

2019-02-20 07:47 UTC, NikhilSuresh24 approved these changes

2019-02-20 07:47 UTC, merged