Elevator code
RoboticsTeam4904/2019-Code pull request #15
Opened 2019-01-15 01:52 UTC by josehrl

2019-01-16 23:46 UTC, oshlern requested changes
It is unclear what the changes are because there is no description

2019-01-17 00:06 UTC, oshlern requested changes
Good stuff. Specific code changes requested.
It would be cool if the constants were commented with units.
Also, add commands! Currently there are no commands to use the elevator.

2019-01-17 00:06 UTC, oshlern commented on src/main/java/org/usfirst/frc4904/robot/subsystems/Elevator.java
> +	public static final double TICK_MULTIPLIER = 360/ENCODER_TICKS;
Integer division in Java will lead to rounding.
In this case, TICK_MULTIPLIER would be 0.

2019-01-17 00:06 UTC, oshlern commented on src/main/java/org/usfirst/frc4904/robot/subsystems/Elevator.java
> +	public static final double ENCODER_TICKS = 1024; //todo: change to real thing
Find the real value (try asking Electronics)

2019-01-17 00:06 UTC, oshlern commented on src/main/java/org/usfirst/frc4904/robot/subsystems/Elevator.java
> +		this.elevEncoder.setDistancePerPulse(TICK_MULTIPLIER);
Kinda messy to do this within Elevator. It should just take in the controllers, because that's what it uses. The encoder should ideally be set in RobotMap (even if that wasn't how it was done last year).
Just realized though, distance per pulse needs to know the physical distance moved, which depends on the elevator. Regardless it should still be possible to set this in RobotMap, and it would make me much happier.

2019-01-17 00:06 UTC, oshlern commented on src/main/java/org/usfirst/frc4904/robot/subsystems/Elevator.java
> +	public static final double TICK_MULTIPLIER = 360/ENCODER_TICKS;
The numerator here corresponds to distance per rotation, not degrees. You could even set that (the distance per rotation) to another variable to make it super clear.

2019-01-17 00:12 UTC, josehrl commented on src/main/java/org/usfirst/frc4904/robot/subsystems/Elevator.java
> +	public static final double ENCODER_TICKS = 1024; //todo: change to real thing
Did it, correct value should be 1024 unless we decide to use different motors for the elevator

2019-02-09 02:24 UTC, NikhilSuresh24 commented
lesser version of fourbar

2019-02-09 02:24 UTC, closed without merging