Climber
RoboticsTeam4904/2019-Code pull request #19
Opened 2019-01-18 01:17 UTC by aksramk

In this branch:

- I added a climbing routine for level 2 
- In the climbing routine, I added four pistons with two solenoids - the solenoids work to prop up the front and back of the robot with the pistons...
- I added a driving PID
- I added chassis code for driving (merged from chassis-code branch)

2019-01-18 01:25 UTC, NikhilSuresh24 requested changes
Overall looks good, just a couple of small changes

2019-01-18 01:25 UTC, NikhilSuresh24 commented on src/main/java/org/usfirst/frc4904/robot/commands/BackLiftSet.java
> +		requires(RobotMap.Component.climber.backLift);
you can require the backlift in the super statement as such

super(clasped ? "BackLiftRetract" : "BackLiftExtend", RobotMap.Component.climber.backLift);

2019-01-18 01:25 UTC, NikhilSuresh24 commented on src/main/java/org/usfirst/frc4904/robot/commands/FrontLiftSet.java
> +		requires(RobotMap.Component.climber.frontLift);
same as above

2019-01-18 01:25 UTC, NikhilSuresh24 commented on src/main/java/org/usfirst/frc4904/robot/commands/FrontLiftSet.java
> +	protected final boolean clasped;
also, name this better, like extended

2019-01-18 01:25 UTC, NikhilSuresh24 commented on src/main/java/org/usfirst/frc4904/robot/subsystems/Climber.java
> +        public void set(boolean fired) {
keep the variable name consistent, i think that extended is a better name for the boolean

2019-01-20 17:44 UTC, billwpierce requested changes
Looks great! most of my changes are just for consistent formatting/clarity for people reading the code later on.

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +            public static final int joystick = 0; //Change port later
this is the one port that you're probably OK not changing

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +            public static final int leftDriveA = 2; // Not real ports, change these
set these all to `-1` until changed

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +            public static final int leftDriveA = 2; // Not real ports, change these
and do that for all ports. And make it a `TODO: ...`

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +            public static final int leftEncoder = -1; // Not real ports, change these
make this a `TODO`

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +            public static final PCMPort shifter = new PCMPort(1, 0, 1);
again, make these `-1` if you don't know them

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +            public static final PCMPort climberFrontLift = new PCMPort(-1, -1, -1); //Define Pneumatics.prongIOPusher with a correct port.
Again, make this a `TODO`!

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +			public static final double TICKS_PER_REVOLUTION = 4.904; // Obviously not real metrics
you can ask electronics and get the actual ticks per revolution

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +			public static final double DIAMETER_INCHES = 4.904;
We already know the diameter (6in), but also double check with design.

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +			public static final double DISTANCE_FRONT_BACK = 4.904;
Set every 4.904 to -1. The only reason we have 49.04 in the code last year was because that was the actual length of the robot.

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +			public static final double P = 0.04; //Tune PID
make these TODO, and only include the comment once.

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +			public static final double P = 0.04; //Tune PID
Also, mention in the TODO that these are the PID values from last year

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +		public static Motor leftWheel;
why is there a random tab???

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/commands/BackLiftSet.java
> +		super(extended ? "BackLiftRetract" : "BackLiftExtend", RobotMap.Component.climber.backLift);
`BackLiftRetract` and `BackLiftExtend` should be switched here, to match the way you defined them in their individual functions.

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/commands/ClimbDistance.java
> +    public static final double WAIT_TIME = 2;
MAKE THESE ALL `-1`, and then make them `TODO:`

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/commands/ClimbDistance.java
> +        super("ClimbDistance"); //Decide whether to do robot alignment on lvl 2, or back away from lvl 2 accurately
make this a `TODO`

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/commands/ClimbDistance.java
> +    public static final double WAIT_TIME = 2;
where is WAIT_TIME used?

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/commands/ClimbDistance.java
> +    public static final double ALMOST_WHEEL_DISTANCE = 2; //Change distance as needed
more descriptive name

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/commands/ClimbTime.java
> +    public static final double FIRST_TIME = 2; //Change time as needed
Yet Again: make these `TODO`, and `-1`

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/commands/ClimbTime.java
> +    public static final double SECOND_TIME = 2; //Change time as needed
make more descriptive double names

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/commands/FrontLiftSet.java
> +		super(extended ? "FrontLiftRetract" : "FrontLiftExtend", RobotMap.Component.climber.frontLift);
Again, make sure to flip `FrontLiftRetract` and `FrontLiftExtend`

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/humaninterface/operators/DefaultOperator.java
> +		RobotMap.HumanInput.Operator.joystick.button1.onlyWhileHeld(new ClimbDistance()); //Use climb with distance (ClimbDistance) or climb with time (ClimbTime)
make this a TODO, and I'd start with `ClimbTime()` (because it's gonna be more reliable

2019-01-20 17:44 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/subsystems/Climber.java
> +        public void set(boolean fired) {
make this `boolean extended` to keep consistent with the `FrontLift`

2019-01-25 01:24 UTC, Krakavius requested changes

2019-01-25 01:24 UTC, Krakavius commented on src/main/java/org/usfirst/frc4904/robot/commands/ClimbDistance.java
> +        addSequential(new ChassisMoveDistance(Component.chassis, BOTH_WHEEL_DISTANCE, Component.drivePID));
For lines 26, 27, and 29, you can't use addSequential since that only allows the next command to run after the current one is completed – however, BackLiftExtend, FrontLiftRetract, and BackLiftRetract extend BackLiftSet/FrontLiftSet, both of which have an isFinished() which always returns false; therefore, the commands after these will never run.

2019-01-25 01:24 UTC, Krakavius commented on src/main/java/org/usfirst/frc4904/robot/commands/ClimbDistance.java
> +        addSequential(new ChassisMoveDistance(Component.chassis, BOTH_WHEEL_DISTANCE, Component.drivePID));
Additionally, you will need to specify the amount of time that it takes for each command to run, as they will all attempt to run instantly with your current code, which won't exactly be what we want to happen (short delay).

2019-02-08 23:55 UTC, billwpierce commented
No longer being used

2019-02-08 23:55 UTC, closed without merging