Set up subsystem prongIO
RoboticsTeam4904/2019-Code pull request #7
Opened 2019-01-08 00:45 UTC by aksramk

Prototype: Three Prong Gripper

This subsystem has one motor and one piston. The motor expands and contracts the three prongs, which can be used while contracted to collect a hatch. They can also be used, while expanded, to contract on a cargo. The piston is used to push out a collected cargo. Everything is set up, but ports, of course, will have to be modified accordingly for testing...

2019-01-08 00:54 UTC, billwpierce requested changes
A few small nitpicks, but nice job!

2019-01-08 00:54 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +            //Define CANMotor.prongIOExpanderMotor with a correct port.
For Todos, add them on the line of the port, with `//TODO: Define with a correct port.`

2019-01-08 00:54 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +            //Define Pneumatics.prongIOPusher with a correct port.
See my TODO-correction above.

2019-01-08 00:54 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/commands/PusherInside.java
> +public class PusherInside extends PusherSet {
Rename this to `PusherRetract`

2019-01-08 00:54 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/commands/PusherSet.java
> +	protected final boolean fired;
rename `fired` to `fire`

2019-01-08 00:54 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/commands/PusherSet.java
> +		return false;
`return true;`

2019-01-08 00:54 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/subsystems/ProngIO.java
> +    //Will change speeds as needed.
Again, see the TODO-correction.

2019-01-08 00:54 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/subsystems/ProngIO.java
> +    public final Pusher pusher;
Fix your indentation!

2019-01-08 00:54 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/subsystems/ProngIO.java
> +		public static final DoubleSolenoid.Value INSIDE = DoubleSolenoid.Value.kReverse;
again, rename to RETRACT

2019-01-08 00:54 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/subsystems/ProngIO.java
> +			super("ProngIO Pusher");
add an underscore or dash

2019-01-08 00:54 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/subsystems/ProngIO.java
> +			if (fired) this.pusher.set(FIRED);
Use regular if statements.

2019-01-08 00:54 UTC, billwpierce commented on src/main/java/org/usfirst/frc4904/robot/subsystems/ProngIO.java
> +		public static final DoubleSolenoid.Value FIRED = DoubleSolenoid.Value.kForward;
add a TODO because we don't know the proper solenoid directions.

2019-01-12 07:01 UTC, NikhilSuresh24 commented on src/main/java/org/usfirst/frc4904/robot/RobotMap.java
> +            public static final int prongIOExpanderMotor=-1; //Define CANMotor.prongIOExpanderMotor with a correct port.
spacing please around equal sign

2019-01-12 17:50 UTC, aksramk commented on src/main/java/org/usfirst/frc4904/robot/commands/PusherSet.java
> +		return false;
About this:

What does this do?

2019-01-31 01:10 UTC, closed without merging